### ISSUE TITLE
fabric 1.18 不能工作

### ISSUE THREAD

**Issue by ajdgsu** [USS-Shenzhou/brighter#1]
我测试了1.18 的fabric版，并不能工作（哪怕只让这一个mod运行）；如果你需要的话可以试试我在用的整合包

https://www.lanzouw.com/inRBVxfp46d

ps:我尝试过使用hmcl整合包导出，但是hmcl貌似默认使用的源 (初始化的时候没法更改) 还没有1.18，不能工作，所以我手动提取了出来，请自行将解压文件放到 .minecraft\versions 下。

**Comment by USS-Shenzhou** [comment]
生产环境不工作是refmap没搞好导致的。已修复并发布新版本**BrighterF-0.1.18-beta.jar**，CurseForge页面正在审核中。稍后进行兼容性测试。

**Comment by USS-Shenzhou** [comment]
经测试与星光（StarLight）不兼容。与元素周期表似乎是兼容的。

**Comment by USS-Shenzhou** [comment]
磷还没有出1.18版本，暂时测不了。不过说实话我很怀疑它的兼容性。
