### ISSUE TITLE
Placing blocks next to lava in nether makes fps drop suddenly

### ISSUE THREAD

**Issue by Awesome23rd** [USS-Shenzhou/brighter#4]
Version 1.20.1
Forge 47.2.17

Hi! I found a bug. When I place blocks near, or at the surface of lava pools in the nether, my fps goes to 1.
I found it while making a modpack, but I replicated it with brighter as the only mod as well.

it also happens when using brighter in combination with Dynamic Lights by Tschipcraft. Holding a torch, in the nether, near lava and moving lags in the same way.

I love the mod, hope you can find a fix!

**Comment by USS-Shenzhou** [comment]
Thank you for your reporting. I'll try to fix this in this week.
(This is a known problem but I thought no one would use this mod, but obviously I was wrong. LOL)

**Comment by Awesome23rd** [comment]
Great! Im using true darkness in my modpack and I thought not knowing what was out there in the dark was awesome, but vanilla torches makes it too hard to navigate. So this mod was perfect. Thank you!
It would also be very cool with a config to fine tune the brightness

**Comment by USS-Shenzhou** [comment]
> It would also be very cool with a config to fine tune the brightness

If you want to adjust the brightness visually, *True Darkness* provides its own config. For actual block light, there is no smooth adjustment because block lights in Minecraft are 16 discrete values (from 0 to 15), only the render system makes them look smoothly.

PS If you found out that the *True Darkness*'s adjustment were not enough, you may use a shaderpack instead.

**Comment by Awesome23rd** [comment]
I will look into it, thanks for the help!

**Comment by USS-Shenzhou** [comment]
It seems that some needed information in program got vanished during the 1.20 light system update. Currently, the only way I found to fix this problem is returning to vanilla block light propagation mode when in nether. You can check my curseforge this weekend for the new version.

**Comment by Awesome23rd** [comment]
Alright, awesome! looking forward to it :D
